version: '3'

services:
  clickhouse-01:
    image: clickhouse-server
    build:
      context: ./server
      args:
        - CLUSTER_NAME=cluster_1S_2R
        - CLUSTER_PASSWORD=password 
        - NODE_NAME=node_1
        - REPLICA=01
        - REPLICA_HOST_1=clickhouse-01
        - REPLICA_HOST_2=clickhouse-02
        - CLICKHOUSE_KEEPER_1=clickhouse-keeper-01
        - CLICKHOUSE_KEEPER_2=clickhouse-keeper-02
        - CLICKHOUSE_KEEPER_3=clickhouse-keeper-03
    container_name: clickhouse-server-1
    hostname: clickhouse-01
    ports:
      - "9001:9000"
      - "8131:8123"
      - "8451:8443"